language: node_js
node_js:
- stable
cache:
  yarn: true
  directories:
  - node_modules
install:
- npm install
script:
- bash ./deploy.sh
notifications:
  slack:
    secure: eyjiyNnIawjgATsAgfxsG/YPZgW0zi9n8nYkgHu3fADMm/rJaNnvajWY1amW8jPtmF7AwlRLKjqPyUzB3tsal3mSxdWIvHfw0jtqtPykmYdsHpI0FM5BGxCchhcPxnHhoTr6ZY/PIPFmq+1rRenJCePd2SYkzvXXFNbDvG7ls67qL1qgbnNU1pm519Hmj+hS/Qxt5LyHaNd4QKJ+NEpW+uiHeH3IFjTVG2Fje9A7a/85FRKUg9mLbR5wfqD/zVT9PCD0AbhMMkAt9fR1WeUTZGincfjHJ51LCBZpYe5/34HA/Jr3Ul+uSzjLTX2LMFhWXTx/q1R1paxTUejRY9R73AmGHbCYkxfNL9nMU4TG/yI5gROXZ4vrNzXr6mkhMLui+Yja64jBpnwyUTBjXsJALT7HOgFouhnp/NsvaF+UjxRqH4AT+DyW0QYQVzNc6cB6b2zd0wMXsnECKs4m2dJEYLRRP6e5pDwb7XnBQW0GxzB/xqF3q4uph/lvPfccyb0L9R5Mq1Bw2/jjTsmhnk7WFpiGEhrji77hqhywzJvgrlGaK/NHUgItkTipKhyXM9YKGC8bcD3OaK+II3avceEAt/rWDq+uG3xa03vv1qLTpen+TADA1QQNF6DtY5iGnf2nK2imcHhMFP2jd7gokD/172xjNgeKpaxtV3V+Rs/IAew=
